name: main
on:
  pull_request:
  push:
    branches:
    - master
    tags:
    - v*
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: install-dependencies
      run: |
        sudo apt-get install -y libgeos-dev postgis postgresql
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a
    - run: go build ./...
    - name: init-database
      run: |
        sudo systemctl start postgresql.service
        sudo -u postgres createuser -s "${USER}"
        createdb "${USER}"
    - run: go test ./...
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: install-dependencies
      run: |
        sudo apt-get install -y libgeos-dev
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a
    - uses: golangci/golangci-lint-action@971e284b6050e8a5849b72094c50ab08da042db8
      with:
        version: v1.60.3
